; HEADER_BLOCK_START
; generated by OrcaSlicer 2.3.2-dev on 2026-01-09 at 16:39:06
; total layer number: 112
; filament_density: 1.24
; filament_diameter: 1.75
; max_z_height: 22.44
; HEADER_BLOCK_END

; external perimeters extrusion width = 0.40mm
; perimeters extrusion width = 0.40mm
; infill extrusion width = 0.40mm
; solid infill extrusion width = 0.50mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.40mm

; EXECUTABLE_BLOCK_START
M73 P0 R500
M201 X10000 Y10000 Z500 E5000
M203 X400 Y400 Z20 E50
M204 P10000 R1000 T0 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E5.00 ; sets the jerk limits, mm/sec
M190 S35 ; set bed temperature and wait for it to be reached
;TYPE:Custom
M104 S200 ; start nozzle heating but don't wait
M109 S200 ; wait for the nozzle to heat up
G28 ; home 
;Prime the extruder